#!/usr/bin/env node-harmony
'use sctrict'

var cerber			= require('cerber')
  , fs				= require('fs')
  , url				= require('url')
  , util			= require('util')
  , crypto			= require('crypto')
  , http			= require('http')
  , errors			= require('errors')
  , Phoenix			= require('phoenix')
  , cql				= require('ncc')
  , cc				= require('cconfig')
  , coroutine		= require('coroutine')
  , ct				= require('ct')

cerber.initService()

http.globalAgent.maxSockets = 200

errors.activateCatcher()

coroutine(function*(params, sv) {

	global.config = JSON.parse(yield fs.readFile(cerber.daemonPath + '/html_builder.config.json', sv.resume))
	var commonConfig = JSON.parse(yield fs.readFile(cerber.daemonPath + '/../config/config.json', sv.resume))

	var branch = process.env.SC_BRANCH || 'trunk'
	console.log('use config branch ' + branch)

	global.config = yield cc.create(config, branch, commonConfig, sv.onlyok)

}, null, function(event, data) {
	if(GE_ERROR === event) {
		console.showError(data)
		process.exit(255)
	}
})

